name: 💡 Feature Request
description: I want to add something to `remix-validated-form`.
title: "[Feature]: "
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!
  - type: textarea
    attributes:
      label: What is the new or updated feature that you are suggesting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why should this feature be included?
    validations:
      required: true
