name: Test and build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image: node:14.3-stretch

    steps:
      - uses: actions/checkout@v2

      - name: Install Deps
        run: npm install

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Cypress Tests
        run:
          - cd ./test-app
          - npm install
          - npm run test
